[package]
name = "day10"
version = "0.1.0"
edition = "2024"

[dependencies]
good_lp = { version = "1.5", features = ["coin_cbc"], default-features = false } # sudo pacman -Sy coin-or-cbc
utils = { path = "../utils" }
